# Generated by Django 5.0 on 2024-04-28 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_slug_alter_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='image',
            new_name='images',
        ),
    ]
